---
# tasks file for php
- name: install php-fpm
  apt:
    name: php-fpm
    state: latest

- name: copy config
  template:
    src: "{{ php_conf_src }}"
    dest: "{{ php_conf_dst }}"
  notify: restart php-fpm

- name: create /var/www
  file:
    path: "{{ root_location }}"
    state: directory

- name: copy info.php
  copy:
    src: "{{ info_php_src }}"
    dest: "{{ info_php_dst }}"
  notify: restart php-fpm

- name: open php port
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 9000
    jump: ACCEPT
