---

- name: install/drop postfix
  hosts: localhost
  become: yes

  tasks:

  - name: install posfix
    apt:
      update-cache: yes
      name: postfix
      state: latest
    tags: init postfix

  - name: drop posfix
    apt:
      name: postfix
      state: absent
    tags: drop postfix
